from django.db import models


class Activity(models.Model):

    class Actor(models.TextChoices):
        MAX = 'max', 'max'
        HERMES = 'hermes', 'hermes'
        SYSTEM = 'system', 'system'

    id = models.UUIDField(primary_key=True)  # Generated by the caller
    project = models.ForeignKey(
        'projects.Project',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='activities',
    )
    event_type = models.CharField(max_length=100)
    object_type = models.CharField(max_length=50)
    object_id = models.UUIDField()
    actor = models.CharField(max_length=10, choices=Actor.choices)
    message = models.CharField(max_length=500)
    occurred_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-occurred_at']
        verbose_name_plural = 'activities'

    def __str__(self):
        return f'{self.event_type} — {self.message[:80]}'
