# Generated by Django 5.2.16 on 2026-07-17 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('exploration', 'Exploration'), ('planned', 'Planifié'), ('active', 'Actif'), ('paused', 'En pause'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='exploration', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('normal', 'Normale'), ('low', 'Basse')], default='normal', max_length=10)),
                ('workspace_path', models.CharField(blank=True, max_length=500)),
                ('repository_url', models.URLField(blank=True, max_length=500)),
                ('primary_url', models.URLField(blank=True, max_length=500)),
                ('review_due_on', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['status', '-priority', '-updated_at'],
            },
        ),
    ]
