# Generated by Django 5.2.16 on 2026-07-17 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField()),
                ('actor', models.CharField(choices=[('max', 'max'), ('hermes', 'hermes'), ('system', 'system')], max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
