# Generated by Django 5.2.16 on 2026-07-17 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('waiting', 'En attente'), ('blocked', 'Bloquée'), ('completed', 'Terminée'), ('canceled', 'Annulée')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('normal', 'Normale'), ('low', 'Basse')], default='normal', max_length=10)),
                ('is_next_action', models.BooleanField(default=False)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('review_on', models.DateField(blank=True, null=True)),
                ('blocker_description', models.TextField(blank=True)),
                ('unblock_action', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, max_length=2000)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_reason', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-is_next_action', '-priority', 'due_on', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_next_action', True)), fields=('project',), name='unique_next_action_per_project')],
            },
        ),
    ]
