# Generated by Django 5.2.16 on 2026-07-17 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('application', 'Application'), ('ai_agent', 'Agent IA'), ('automation', 'Automatisation'), ('repository', 'Dépôt'), ('external_service', 'Service externe'), ('infrastructure', 'Infrastructure')], max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('active', 'Actif'), ('degraded', 'Dégradé'), ('inactive', 'Inactif'), ('retired', 'Retiré')], default='planned', max_length=20)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.project')),
            ],
            options={
                'ordering': ['asset_type', 'name'],
            },
        ),
    ]
