# Generated by Django 5.2.16 on 2026-07-17 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('resource_type', models.CharField(choices=[('note', 'Note'), ('idea', 'Idée'), ('document', 'Document'), ('prompt', 'Prompt'), ('procedure', 'Procédure'), ('reference', 'Référence')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
