# Generated by Django 5.2.16 on 2026-07-17 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('suggested_type', models.CharField(blank=True, choices=[('idea', 'Idée'), ('task', 'Tâche'), ('decision', 'Décision'), ('resource', 'Ressource'), ('other', 'Autre')], max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('unprocessed', 'À traiter'), ('processed', 'Traité'), ('discarded', 'Écarté')], default='unprocessed', max_length=20)),
                ('discarded_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('destination_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_processed', to='projects.project')),
                ('suggested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_suggestions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
