# Generated by Django 5.2.16 on 2026-07-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
        ('inbox', '0001_initial'),
        ('resources', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='destination_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_origin', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='destination_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_origin', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='destination_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_origin', to='tasks.task'),
        ),
    ]
