# Generated by Django 5.2.16 on 2026-07-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inboxitem_destination_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
