# Generated by Django 5.2.16 on 2026-07-17 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('context', models.TextField()),
                ('question', models.TextField()),
                ('choice', models.TextField(blank=True)),
                ('alternatives', models.TextField(blank=True)),
                ('consequences', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('superseded', 'Remplacée')], default='proposed', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='projects.project')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='decisions.decision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
