# Generated by Django 5.2.16 on 2026-07-17 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('prepared', 'Préparée'), ('released', 'Livrée'), ('validated', 'Validée'), ('failed', 'Échouée'), ('withdrawn', 'Retirée')], default='prepared', max_length=20)),
                ('summary', models.TextField()),
                ('reference_url', models.URLField(blank=True, max_length=2000)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('validation_result', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='registry.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='projects.project')),
            ],
            options={
                'ordering': ['-released_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'version_label'), name='unique_version_per_project')],
            },
        ),
    ]
